# Generated by Django 5.1.5 on 2025-02-22 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Doctor'), (3, 'Patient')])),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], default='Mr', max_length=5)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='doctor_id_proofs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='unmarried', max_length=10)),
                ('joining_date', models.DateField()),
                ('resignation_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('reliving_date', models.DateField(blank=True, null=True)),
                ('rejoining_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('qualifications', models.TextField()),
                ('qualification_certificate', models.FileField(blank=True, null=True, upload_to='qualification_certificates/')),
                ('experience_years', models.PositiveIntegerField()),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='experience_certificates/')),
                ('medical_registration_number', models.CharField(max_length=100)),
                ('medical_registration_certificate', models.FileField(blank=True, null=True, upload_to='medical_certificates/')),
                ('login_status', models.BooleanField(default=False)),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('rejoined', 'Rejoined')], default='active', max_length=10)),
                ('fk_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='admin_care.departments')),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('login_status', models.BooleanField(default=False)),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
