# Generated by Django 5.1.5 on 2025-02-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='unmarried', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('other', 'Other')], default='self', max_length=10)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('existing_conditions', models.TextField(blank=True, null=True)),
                ('ongoing_medications', models.TextField(blank=True, null=True)),
                ('previous_surgeries', models.TextField(blank=True, null=True)),
                ('medical_report_file', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(blank=True, max_length=15, unique=True)),
                ('fk_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='admin_care.patient')),
            ],
        ),
    ]
