# Generated by Django 5.1.5 on 2025-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0002_medicalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='relationship',
            field=models.CharField(choices=[('self', 'Self'), ('mother', 'Mother'), ('father', 'Father'), ('child', 'Child'), ('wife', 'Wife'), ('husband', 'Husband'), ('other', 'Other')], default='self', max_length=10),
        ),
    ]
