# Generated by Django 5.1.6 on 2025-02-27 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0003_alter_medicalreport_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('noon', 'Noon'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='admin_care.doctor')),
            ],
            options={
                'verbose_name_plural': 'Doctor Availabilities',
                'unique_together': {('doctor', 'shift', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('slot_count', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(25)])),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='admin_care.doctoravailable')),
            ],
            options={
                'unique_together': {('availability', 'day')},
            },
        ),
    ]
