# Generated by Django 5.1.6 on 2025-03-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0004_doctoravailable_doctoravailableslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('patient_mr', models.CharField(blank=True, max_length=15)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.patient')),
            ],
        ),
    ]
