# Generated by Django 5.1.6 on 2025-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='known_diseases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
