# Generated by Django 5.1.6 on 2025-03-03 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0008_alter_customuser_role_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Doctor'), (3, 'Patient'), (4, 'Nurse'), (5, 'Pharamcist')]),
        ),
        migrations.CreateModel(
            name='Pharamcist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], default='Mr', max_length=5)),
                ('pharmacist_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='pharmacist_id_proofs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharamacist_images/')),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='unmarried', max_length=10)),
                ('joining_date', models.DateField()),
                ('resignation_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('reliving_date', models.DateField(blank=True, null=True)),
                ('rejoining_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('qualifications', models.TextField()),
                ('qualification_certificate', models.FileField(blank=True, null=True, upload_to='qualification_certificates/')),
                ('experience_years', models.PositiveIntegerField()),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='experience_certificates/')),
                ('medical_registration_number', models.CharField(max_length=100)),
                ('medical_registration_certificate', models.FileField(blank=True, null=True, upload_to='medical_certificates/')),
                ('login_status', models.BooleanField(default=False)),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('rejoined', 'Rejoined')], default='active', max_length=10)),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharamacist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
