# Generated by Django 5.1.6 on 2025-03-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0009_alter_customuser_role_pharamcist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharamcist',
            name='pharmacist_name',
        ),
    ]
