# Generated by Django 5.1.6 on 2025-03-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0011_alter_customuser_role_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='fk_dep',
        ),
    ]
