# Generated by Django 5.1.6 on 2025-03-08 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0014_category_medicine_manufacture_medicine_name_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('cbc', 'Complete Blood Count (CBC)'), ('fbs', 'Fasting Blood Sugar (FBS)'), ('hba1c', 'Hemoglobin A1C (HbA1c)'), ('lipid_panel', 'Lipid Panel (Cholesterol Test)'), ('tsh', 'Thyroid Stimulating Hormone (TSH)'), ('t3_t4', 'T3 & T4 Thyroid Test'), ('electrolytes', 'Electrolyte Panel'), ('lft', 'Liver Function Test (LFT)'), ('rft', 'Renal Function Test (RFT)'), ('crp', 'C-Reactive Protein (CRP)'), ('urinalysis', 'Urinalysis'), ('urine_culture', 'Urine Culture Test'), ('occult_blood', 'Stool Occult Blood Test'), ('fecal_fat', 'Fecal Fat Test'), ('fecal_elastase', 'Fecal Elastase Test'), ('genetic_dna', 'Genetic DNA Testing'), ('covid_pcr', 'COVID-19 PCR Test'), ('allergy_igg', 'Allergy IgG & IgE Panel')], max_length=255)),
                ('test_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('stool_test', 'Stool Test'), ('genetic_test', 'Genetic Test'), ('covid_test', 'COVID-19 Test'), ('allergy_test', 'Allergy Test')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lab_tests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
