# Generated by Django 5.1.6 on 2025-03-08 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0015_labtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('imaging', 'Imaging Test'), ('cardiology', 'Cardiology Test'), ('neurology', 'Neurology Test'), ('orthopedic', 'Orthopedic Test'), ('vascular', 'Vascular Test')], max_length=50)),
                ('test_name', models.CharField(choices=[('xray', 'X-ray'), ('ct_scan', 'CT Scan'), ('mri', 'MRI (Magnetic Resonance Imaging)'), ('ultrasound', 'Ultrasound'), ('mammogram', 'Mammogram'), ('pet_scan', 'PET Scan (Positron Emission Tomography)'), ('bone_scan', 'Bone Scan'), ('echocardiogram', 'Echocardiogram'), ('doppler_ultrasound', 'Doppler Ultrasound'), ('fluoroscopy', 'Fluoroscopy'), ('angiography', 'Angiography')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
