# Generated by Django 5.1.6 on 2025-03-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0016_radiotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('OD', 'Once a Day'), ('BD', 'Twice a Day'), ('TD', 'Three Times a Day')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.category_medicine')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.doctor')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_care.labtest')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.med')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_care.radiotest')),
            ],
        ),
    ]
