# Generated by Django 5.1.6 on 2025-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0017_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='radio',
        ),
        migrations.AddField(
            model_name='prescription',
            name='lab',
            field=models.ManyToManyField(blank=True, null=True, to='admin_care.labtest'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='radio',
            field=models.ManyToManyField(blank=True, null=True, to='admin_care.radiotest'),
        ),
    ]
