# Generated by Django 5.1.6 on 2025-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0018_remove_prescription_lab_remove_prescription_radio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
