# Generated by Django 3.1.12 on 2025-03-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0020_auto_20250314_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio_TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result_analysis', models.TextField()),
                ('test_upload', models.FileField(upload_to='test_reports/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.radiotest')),
            ],
        ),
    ]
