# Generated by Django 3.1.12 on 2025-03-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0022_testreport_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio_testreport',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_care.prescription'),
        ),
    ]
