# Generated by Django 3.1.12 on 2025-03-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0023_radio_testreport_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.med')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_medicines', to='admin_care.prescription')),
            ],
        ),
    ]
