# Generated by Django 5.1.7 on 2025-03-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0024_medicineprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category_medicine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctoravailable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctoravailableslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorcancellation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='med',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicine_name',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicineprocess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientcancellation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharamcist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='radio_testreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='radiotest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(choices=[('Ward 1 - Floor 1', 'Ward 1 - Floor 1'), ('Ward 2 - Floor 2', 'Ward 2 - Floor 2'), ('Ward 3 - Floor 3', 'Ward 3 - Floor 3'), ('Ward 4 - Floor 4', 'Ward 4 - Floor 4'), ('Ward 5 - Floor 5', 'Ward 5 - Floor 5'), ('Ward 6 - Floor 6', 'Ward 6 - Floor 6'), ('Ward 7 - Floor 7', 'Ward 7 - Floor 7'), ('Ward 8 - Floor 8', 'Ward 8 - Floor 8'), ('Ward 9 - Floor 9', 'Ward 9 - Floor 9'), ('Ward 10 - Floor 10', 'Ward 10 - Floor 10'), ('Ward 11 - Floor 11', 'Ward 11 - Floor 11'), ('Ward 12 - Floor 12', 'Ward 12 - Floor 12'), ('Ward 13 - Floor 13', 'Ward 13 - Floor 13'), ('Ward 14 - Floor 14', 'Ward 14 - Floor 14'), ('Ward 15 - Floor 15', 'Ward 15 - Floor 15'), ('Ward 16 - Floor 16', 'Ward 16 - Floor 16'), ('Ward 17 - Floor 17', 'Ward 17 - Floor 17'), ('Ward 18 - Floor 18', 'Ward 18 - Floor 18'), ('Ward 19 - Floor 19', 'Ward 19 - Floor 19'), ('Ward 20 - Floor 20', 'Ward 20 - Floor 20'), ('Ward 21 - Floor 21', 'Ward 21 - Floor 21'), ('Ward 22 - Floor 22', 'Ward 22 - Floor 22'), ('Ward 23 - Floor 23', 'Ward 23 - Floor 23'), ('Ward 24 - Floor 24', 'Ward 24 - Floor 24'), ('Ward 25 - Floor 25', 'Ward 25 - Floor 25'), ('Ward 26 - Floor 26', 'Ward 26 - Floor 26'), ('Ward 27 - Floor 27', 'Ward 27 - Floor 27'), ('Ward 28 - Floor 28', 'Ward 28 - Floor 28'), ('Ward 29 - Floor 29', 'Ward 29 - Floor 29'), ('Ward 30 - Floor 30', 'Ward 30 - Floor 30'), ('Ward 31 - Floor 1', 'Ward 31 - Floor 1'), ('Ward 32 - Floor 2', 'Ward 32 - Floor 2'), ('Ward 33 - Floor 3', 'Ward 33 - Floor 3'), ('Ward 34 - Floor 4', 'Ward 34 - Floor 4'), ('Ward 35 - Floor 5', 'Ward 35 - Floor 5'), ('Ward 36 - Floor 6', 'Ward 36 - Floor 6'), ('Ward 37 - Floor 7', 'Ward 37 - Floor 7'), ('Ward 38 - Floor 8', 'Ward 38 - Floor 8'), ('Ward 39 - Floor 9', 'Ward 39 - Floor 9'), ('Ward 40 - Floor 10', 'Ward 40 - Floor 10'), ('Ward 41 - Floor 11', 'Ward 41 - Floor 11'), ('Ward 42 - Floor 12', 'Ward 42 - Floor 12'), ('Ward 43 - Floor 13', 'Ward 43 - Floor 13'), ('Ward 44 - Floor 14', 'Ward 44 - Floor 14'), ('Ward 45 - Floor 15', 'Ward 45 - Floor 15'), ('Ward 46 - Floor 16', 'Ward 46 - Floor 16'), ('Ward 47 - Floor 17', 'Ward 47 - Floor 17'), ('Ward 48 - Floor 18', 'Ward 48 - Floor 18'), ('Ward 49 - Floor 19', 'Ward 49 - Floor 19'), ('Ward 50 - Floor 20', 'Ward 50 - Floor 20'), ('Ward 51 - Floor 21', 'Ward 51 - Floor 21'), ('Ward 52 - Floor 22', 'Ward 52 - Floor 22'), ('Ward 53 - Floor 23', 'Ward 53 - Floor 23'), ('Ward 54 - Floor 24', 'Ward 54 - Floor 24'), ('Ward 55 - Floor 25', 'Ward 55 - Floor 25'), ('Ward 56 - Floor 26', 'Ward 56 - Floor 26'), ('Ward 57 - Floor 27', 'Ward 57 - Floor 27'), ('Ward 58 - Floor 28', 'Ward 58 - Floor 28'), ('Ward 59 - Floor 29', 'Ward 59 - Floor 29'), ('Ward 60 - Floor 30', 'Ward 60 - Floor 30'), ('Ward 61 - Floor 1', 'Ward 61 - Floor 1'), ('Ward 62 - Floor 2', 'Ward 62 - Floor 2'), ('Ward 63 - Floor 3', 'Ward 63 - Floor 3'), ('Ward 64 - Floor 4', 'Ward 64 - Floor 4'), ('Ward 65 - Floor 5', 'Ward 65 - Floor 5'), ('Ward 66 - Floor 6', 'Ward 66 - Floor 6'), ('Ward 67 - Floor 7', 'Ward 67 - Floor 7'), ('Ward 68 - Floor 8', 'Ward 68 - Floor 8'), ('Ward 69 - Floor 9', 'Ward 69 - Floor 9'), ('Ward 70 - Floor 10', 'Ward 70 - Floor 10'), ('Ward 71 - Floor 11', 'Ward 71 - Floor 11'), ('Ward 72 - Floor 12', 'Ward 72 - Floor 12'), ('Ward 73 - Floor 13', 'Ward 73 - Floor 13'), ('Ward 74 - Floor 14', 'Ward 74 - Floor 14'), ('Ward 75 - Floor 15', 'Ward 75 - Floor 15'), ('Ward 76 - Floor 16', 'Ward 76 - Floor 16'), ('Ward 77 - Floor 17', 'Ward 77 - Floor 17'), ('Ward 78 - Floor 18', 'Ward 78 - Floor 18'), ('Ward 79 - Floor 19', 'Ward 79 - Floor 19'), ('Ward 80 - Floor 20', 'Ward 80 - Floor 20'), ('Ward 81 - Floor 21', 'Ward 81 - Floor 21'), ('Ward 82 - Floor 22', 'Ward 82 - Floor 22'), ('Ward 83 - Floor 23', 'Ward 83 - Floor 23'), ('Ward 84 - Floor 24', 'Ward 84 - Floor 24'), ('Ward 85 - Floor 25', 'Ward 85 - Floor 25'), ('Ward 86 - Floor 26', 'Ward 86 - Floor 26'), ('Ward 87 - Floor 27', 'Ward 87 - Floor 27'), ('Ward 88 - Floor 28', 'Ward 88 - Floor 28'), ('Ward 89 - Floor 29', 'Ward 89 - Floor 29'), ('Ward 90 - Floor 30', 'Ward 90 - Floor 30'), ('Ward 91 - Floor 1', 'Ward 91 - Floor 1'), ('Ward 92 - Floor 2', 'Ward 92 - Floor 2'), ('Ward 93 - Floor 3', 'Ward 93 - Floor 3'), ('Ward 94 - Floor 4', 'Ward 94 - Floor 4'), ('Ward 95 - Floor 5', 'Ward 95 - Floor 5'), ('Ward 96 - Floor 6', 'Ward 96 - Floor 6'), ('Ward 97 - Floor 7', 'Ward 97 - Floor 7'), ('Ward 98 - Floor 8', 'Ward 98 - Floor 8'), ('Ward 99 - Floor 9', 'Ward 99 - Floor 9'), ('Ward 100 - Floor 10', 'Ward 100 - Floor 10')], max_length=50)),
                ('bed_number', models.CharField(max_length=10)),
                ('admission_date', models.DateField()),
                ('admission_reason', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('assigned_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_care.nurse')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.prescription')),
            ],
        ),
    ]
