# Generated by Django 5.1.7 on 2025-03-24 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0025_alter_appointment_id_alter_category_medicine_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('consulted_department', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=50)),
                ('bed_number', models.CharField(max_length=10)),
                ('assigned_date', models.DateField()),
                ('admission_date', models.DateField()),
                ('admission_reason', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('respiratory_rate', models.IntegerField()),
                ('oxygen_level', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ward_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.wardassignment')),
            ],
        ),
    ]
