# Generated by Django 5.1.7 on 2025-03-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0026_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation_Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('respiratory_rate', models.IntegerField()),
                ('oxygen_level', models.FloatField()),
                ('discharge_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ward_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.wardassignment')),
            ],
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
