# Generated by Django 5.1.7 on 2025-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0027_documentation_patient_delete_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation_patient',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentation_patient',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentation_patient',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentation_patient',
            name='oxygen_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentation_patient',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentation_patient',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
