# Generated by Django 5.1.7 on 2025-03-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0030_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.testreport')),
                ('fk_med_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.medicineprocess')),
                ('fk_radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.radio_testreport')),
            ],
        ),
    ]
