# Generated by Django 5.1.7 on 2025-03-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0031_report_g'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('radio_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fk_lab_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_care.testreport')),
                ('fk_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.medicalreport')),
                ('fk_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_care.prescription')),
                ('fk_radio_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_care.radio_testreport')),
            ],
        ),
    ]
