# Generated by Django 5.1.7 on 2025-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0032_reportprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('lab_reports', models.TextField()),
                ('radio_reports', models.TextField()),
                ('medicines', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_date', models.DateField()),
            ],
        ),
    ]
