# Generated by Django 5.1.7 on 2025-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_care', '0033_final_patientreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_patientreport',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
